import { z } from 'zod';

export const mqttResponseBaseSchema = z.object({
    cmdId: z.number().int(),
    cmdFunc: z.number().int(),
    param: z.record(z.string(), z.any()).optional(),
    addr: z.string()
}).passthrough();

// cmdId: 1,
// cmdFunc: 2,
// param: { ... },
// addr: 'hs_yj751_pd_appshow_addr'
export const mqttResponseCmdId1Params = z.object({
    access5p8InType: z.number().int().optional(),
    access5p8OutType: z.number().int().optional(),
    accessType: z.number().int().optional(),
    bpNum: z.number().int().optional(),
    c20ChgMaxWatts: z.number().int().optional(),
    chgTimeTaskMode: z.number().int().optional(),
    chgTimeTaskNotice: z.number().int().optional(),
    chgTimeTaskParam: z.number().int().optional(),
    chgTimeTaskTable0: z.number().int().optional(),
    chgTimeTaskTable1: z.number().int().optional(),
    chgTimeTaskTable2: z.number().int().optional(),
    chgTimeTaskType: z.number().int().optional(),
    dsgTimeTaskMode: z.number().int().optional(),
    dsgTimeTaskNotice: z.number().int().optional(),
    dsgTimeTaskParam: z.number().int().optional(),
    dsgTimeTaskTable0: z.number().int().optional(),
    dsgTimeTaskTable1: z.number().int().optional(),
    dsgTimeTaskTable2: z.number().int().optional(),
    dsgTimeTaskType: z.number().int().optional(),
    fullCombo: z.number().int().optional(),
    inAc5p8Pwr: z.number().optional(),
    inAcC20Pwr: z.number().optional(),
    inHvMpptPwr: z.number().optional(),
    inLvMpptPwr: z.number().optional(),
    outAc5p8Pwr: z.number().optional(),
    outAcL11Pwr: z.number().optional(),
    outAcL12Pwr: z.number().optional(),
    outAcL14Pwr: z.number().optional(),
    outAcL21Pwr: z.number().optional(),
    outAcL22Pwr: z.number().optional(),
    outAcTtPwr: z.number().optional(),
    outAdsPwr: z.number().optional(),
    outPrPwr: z.number().optional(),
    outTypec1Pwr: z.number().optional(),
    outTypec2Pwr: z.number().optional(),
    outUsb1Pwr: z.number().optional(),
    outUsb2Pwr: z.number().optional(),
    paraChgMaxWatts: z.number().int().optional(),
    pcsType: z.number().int().optional(),
    remainCombo: z.number().int().optional(),
    remainTime: z.number().int().optional(),
    showFlag: z.number().int().optional(),
    soc: z.number().int().optional(),
    sysErrCode: z.number().int().optional(),
    wattsInSum: z.number().optional(),
    wattsOutSum: z.number().optional(),
    wireless4gCon: z.number().int().optional(),
    wireless4gOn: z.number().int().optional(),
    wireless4GSta: z.number().int().optional(),
    wirlesss4gErrCode: z.number().int().optional()
}).passthrough();

// cmdId: 2
// cmdFunc: 2
// param: { ... }
// addr: 'hs_yj751_pd_backend_addr'
export const mqttResponseCmdId2Params = z.object({
    acOutFreq: z.number().int().optional(),
    batAmp: z.number().optional(),
    batVol: z.number().optional(),
    bmsInputWatts: z.number().optional(),
    bmsOutputWatts: z.number().optional(),
    inAc5p8Vol: z.number().optional(),
    inAcC20Vol: z.number().optional(),
    inHvMpptVol: z.number().optional(),
    inLvMpptVol: z.number().optional()
}).passthrough();

// cmdId: 3
// cmdFunc: 2
// param: { ... }
// addr: 'hs_yj751_pd_app_set_info_addr'
export const mqttResponseCmdId3Params = z.object({
    acOftenOpenFlg: z.number().int().optional(),
    acOftenOpenMinSoc: z.number().int().optional(),
    acOutFreq: z.number().int().optional(),
    acStandbyMins: z.number().int().optional(),
    acXboost: z.number().int().optional(),
    backupRatio: z.number().int().optional(),
    bmsModeSet: z.number().int().optional(),
    chg5p8SetWatts: z.number().int().optional(),
    chgC20SetWatts: z.number().int().optional(),
    chgMaxSoc: z.number().int().optional(),
    dcStandbyMins: z.number().int().optional(),
    dsgMinSoc: z.number().int().optional(),
    energyMamageEnable: z.number().int().optional(),
    powerStandbyMins: z.number().int().optional(),
    screenStandbySec: z.number().int().optional(),
    solarOnlyFlg: z.number().int().optional(),
    sysBackupEvent: z.number().int().optional(),
    sysBackupSoc: z.number().int().optional(),
    sysTimezone: z.number().int().optional(),
    sysTimezoneId: z.string().optional(),
    sysWordMode: z.number().int().optional(),
    timezoneSettype: z.number().int().optional()
}).passthrough();

export const restAllQuotaData = z.object({
    'hs_yj751_pd_appshow_addr.access5p8InType': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.access5p8OutType': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.accessType': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.bpNum': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.c20ChgMaxWatts': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.chgTimeTaskMode': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.chgTimeTaskNotice': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.chgTimeTaskParam': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.chgTimeTaskTable0': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.chgTimeTaskTable1': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.chgTimeTaskTable2': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.chgTimeTaskType': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.dsgTimeTaskMode': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.dsgTimeTaskNotice': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.dsgTimeTaskParam': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.dsgTimeTaskTable0': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.dsgTimeTaskTable1': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.dsgTimeTaskTable2': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.dsgTimeTaskType': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.fullCombo': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.inAc5p8Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.inAcC20Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.inHvMpptPwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.inLvMpptPwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAc5p8Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAcL11Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAcL12Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAcL14Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAcL21Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAcL22Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAcTtPwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outAdsPwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outPrPwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outTypec1Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outTypec2Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outUsb1Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.outUsb2Pwr': z.number().optional(),
    'hs_yj751_pd_appshow_addr.paraChgMaxWatts': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.pcsType': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.remainCombo': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.remainTime': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.showFlag': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.soc': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.sysErrCode': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.updateTime': z.string().optional(),
    'hs_yj751_pd_appshow_addr.wattsInSum': z.number().optional(),
    'hs_yj751_pd_appshow_addr.wattsOutSum': z.number().optional(),
    'hs_yj751_pd_appshow_addr.wireless4gCon': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.wireless4gOn': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.wireless4GSta': z.number().int().optional(),
    'hs_yj751_pd_appshow_addr.wirlesss4gErrCode': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.acInFreq': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.acOutFreq': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.adsErrCode': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.batAmp': z.number().optional(),
    'hs_yj751_pd_backend_addr.batVol': z.number().optional(),
    'hs_yj751_pd_backend_addr.bmsInputWatts': z.number().optional(),
    'hs_yj751_pd_backend_addr.bmsOutputWatts': z.number().optional(),
    'hs_yj751_pd_backend_addr.c20InType': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.chgReignSta': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.emsMaxAvailNum': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.emsOpenBmsIdx': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.emsParaVolMax': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.emsParaVolMin': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.emsWorkSta': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.evMaxChargerCur': z.number().optional(),
    'hs_yj751_pd_backend_addr.fanState': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.hvPvErrCode': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.inAc5p8Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.inAc5p8Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.inAcC20Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.inAcC20Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.inHvMpptAmp': z.number().optional(),
    'hs_yj751_pd_backend_addr.inHvMpptVol': z.number().optional(),
    'hs_yj751_pd_backend_addr.inLvMpptAmp': z.number().optional(),
    'hs_yj751_pd_backend_addr.inLvMpptVol': z.number().optional(),
    'hs_yj751_pd_backend_addr.lvPvErrCode': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.mpptHvTemp': z.number().optional(),
    'hs_yj751_pd_backend_addr.mpptLvTemp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAc5p8Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAc5p8Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL11Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL11Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL12Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL12Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL14Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL14Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL21Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL21Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL22Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcL22Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcTtAmp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAcTtVol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAdsAmp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outAdsVol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outTypec1Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outTypec1Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outTypec2Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outTypec2Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outUsb1Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outUsb1Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.outUsb2Amp': z.number().optional(),
    'hs_yj751_pd_backend_addr.outUsb2Vol': z.number().optional(),
    'hs_yj751_pd_backend_addr.pcsAcErrCode': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.pcsAcTemp': z.number().optional(),
    'hs_yj751_pd_backend_addr.pcsDcErrCode': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.pcsDcTemp': z.number().optional(),
    'hs_yj751_pd_backend_addr.pcsWorkSta': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.pdTemp': z.number().optional(),
    'hs_yj751_pd_backend_addr.recordFlag': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.sysWorkSta': z.number().int().optional(),
    'hs_yj751_pd_backend_addr.updateTime': z.string().optional(),
    'hs_yj751_pd_backend_addr.work5p8Mode': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.acOftenOpenFlg': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.acOftenOpenMinSoc': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.acOutFreq': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.acStandbyMins': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.acXboost': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.backupRatio': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.bmsModeSet': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.chg5p8SetWatts': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.chgC20SetWatts': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.chgMaxSoc': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.dcStandbyMins': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.dsgMinSoc': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.energyMamageEnable': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.powerStandbyMins': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.screenStandbySec': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.solarOnlyFlg': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.sysBackupEvent': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.sysBackupSoc': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.sysTimezone': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.sysTimezoneId': z.string().optional(),
    'hs_yj751_pd_app_set_info_addr.sysWordMode': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.timezoneSettype': z.number().int().optional(),
    'hs_yj751_pd_app_set_info_addr.updateTime': z.string().optional(),
    'hs_yj751_pd_bp_addr.bpInfo': z.array(z.object({
        bpNo: z.number().int().optional(),
        bpChgSta: z.number().int().optional(),
        bpSoc: z.number().int().optional(),
        bpPwr: z.number().optional(),
        bpEnergy: z.number().optional(),
        heatTime: z.number().int().optional(),
        remainTime: z.number().int().optional(),
        bpSocMax: z.number().int().optional(),
        bpSocMin: z.number().int().optional(),
        bpErrCode: z.number().int().optional(),
        bpTemp: z.number().optional()
    })).optional(),
    'hs_yj751_pd_bp_addr.updateTime': z.string().optional()
}).passthrough();
